# Generated by Django 6.1 on 2026-08-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_ref', models.CharField(blank=True, max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=20)),
                ('payment_amt', models.FloatField()),
                ('booked_for', models.DateTimeField()),
                ('booked_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
